package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AllVendorAcceptedBookingsId generated by hbm2java
 */
@Embeddable
public class AllVendorAcceptedBookingsId  implements java.io.Serializable {


     private long vendorId;
     private long bookingId;
     private Date startDate;
     private Date startTime;
     private String brandName;
     private String modelName;
     private String vehicleNumber;
     private String formattedAddress;

    public AllVendorAcceptedBookingsId() {
    }

	
    public AllVendorAcceptedBookingsId(long vendorId, long bookingId, String modelName) {
        this.vendorId = vendorId;
        this.bookingId = bookingId;
        this.modelName = modelName;
    }
    public AllVendorAcceptedBookingsId(long vendorId, long bookingId, Date startDate, Date startTime, String brandName, String modelName, String vehicleNumber, String formattedAddress) {
       this.vendorId = vendorId;
       this.bookingId = bookingId;
       this.startDate = startDate;
       this.startTime = startTime;
       this.brandName = brandName;
       this.modelName = modelName;
       this.vehicleNumber = vehicleNumber;
       this.formattedAddress = formattedAddress;
    }
   


    @Column(name="vendor_id", nullable=false)
    public long getVendorId() {
        return this.vendorId;
    }
    
    public void setVendorId(long vendorId) {
        this.vendorId = vendorId;
    }


    @Column(name="booking_id", nullable=false)
    public long getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(long bookingId) {
        this.bookingId = bookingId;
    }


    @Column(name="start_date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }


    @Column(name="start_time", length=8)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }


    @Column(name="brand_name", length=100)
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }


    @Column(name="model_name", nullable=false, length=100)
    public String getModelName() {
        return this.modelName;
    }
    
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }


    @Column(name="vehicle_number", length=100)
    public String getVehicleNumber() {
        return this.vehicleNumber;
    }
    
    public void setVehicleNumber(String vehicleNumber) {
        this.vehicleNumber = vehicleNumber;
    }


    @Column(name="formatted_address", length=65535)
    public String getFormattedAddress() {
        return this.formattedAddress;
    }
    
    public void setFormattedAddress(String formattedAddress) {
        this.formattedAddress = formattedAddress;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AllVendorAcceptedBookingsId) ) return false;
		 AllVendorAcceptedBookingsId castOther = ( AllVendorAcceptedBookingsId ) other; 
         
		 return (this.getVendorId()==castOther.getVendorId())
 && (this.getBookingId()==castOther.getBookingId())
 && ( (this.getStartDate()==castOther.getStartDate()) || ( this.getStartDate()!=null && castOther.getStartDate()!=null && this.getStartDate().equals(castOther.getStartDate()) ) )
 && ( (this.getStartTime()==castOther.getStartTime()) || ( this.getStartTime()!=null && castOther.getStartTime()!=null && this.getStartTime().equals(castOther.getStartTime()) ) )
 && ( (this.getBrandName()==castOther.getBrandName()) || ( this.getBrandName()!=null && castOther.getBrandName()!=null && this.getBrandName().equals(castOther.getBrandName()) ) )
 && ( (this.getModelName()==castOther.getModelName()) || ( this.getModelName()!=null && castOther.getModelName()!=null && this.getModelName().equals(castOther.getModelName()) ) )
 && ( (this.getVehicleNumber()==castOther.getVehicleNumber()) || ( this.getVehicleNumber()!=null && castOther.getVehicleNumber()!=null && this.getVehicleNumber().equals(castOther.getVehicleNumber()) ) )
 && ( (this.getFormattedAddress()==castOther.getFormattedAddress()) || ( this.getFormattedAddress()!=null && castOther.getFormattedAddress()!=null && this.getFormattedAddress().equals(castOther.getFormattedAddress()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getVendorId();
         result = 37 * result + (int) this.getBookingId();
         result = 37 * result + ( getStartDate() == null ? 0 : this.getStartDate().hashCode() );
         result = 37 * result + ( getStartTime() == null ? 0 : this.getStartTime().hashCode() );
         result = 37 * result + ( getBrandName() == null ? 0 : this.getBrandName().hashCode() );
         result = 37 * result + ( getModelName() == null ? 0 : this.getModelName().hashCode() );
         result = 37 * result + ( getVehicleNumber() == null ? 0 : this.getVehicleNumber().hashCode() );
         result = 37 * result + ( getFormattedAddress() == null ? 0 : this.getFormattedAddress().hashCode() );
         return result;
   }   


}


