package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AllVendorAcceptedBookings generated by hbm2java
 */
@Entity
@Table(name="all_vendor_accepted_bookings"
    ,catalog="kemuvin"
)
public class AllVendorAcceptedBookings  implements java.io.Serializable {


     private AllVendorAcceptedBookingsId id;

    public AllVendorAcceptedBookings() {
    }

    public AllVendorAcceptedBookings(AllVendorAcceptedBookingsId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vendorId", column=@Column(name="vendor_id", nullable=false) ), 
        @AttributeOverride(name="bookingId", column=@Column(name="booking_id", nullable=false) ), 
        @AttributeOverride(name="startDate", column=@Column(name="start_date", length=10) ), 
        @AttributeOverride(name="startTime", column=@Column(name="start_time", length=8) ), 
        @AttributeOverride(name="brandName", column=@Column(name="brand_name", length=100) ), 
        @AttributeOverride(name="modelName", column=@Column(name="model_name", nullable=false, length=100) ), 
        @AttributeOverride(name="vehicleNumber", column=@Column(name="vehicle_number", length=100) ), 
        @AttributeOverride(name="formattedAddress", column=@Column(name="formatted_address", length=65535) ) } )
    public AllVendorAcceptedBookingsId getId() {
        return this.id;
    }
    
    public void setId(AllVendorAcceptedBookingsId id) {
        this.id = id;
    }




}


