package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BookingTrackingStatus generated by hbm2java
 */
@Entity
@Table(name="booking_tracking_status"
    ,catalog="kemuvin"
)
public class BookingTrackingStatus  implements java.io.Serializable {


     private Integer bookingTrackingStatusId;
     private String statusName;
     private Set<BookingTracking> bookingTrackings = new HashSet<BookingTracking>(0);

    public BookingTrackingStatus() {
    }

    public BookingTrackingStatus(String statusName, Set<BookingTracking> bookingTrackings) {
       this.statusName = statusName;
       this.bookingTrackings = bookingTrackings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="booking_tracking_status_id", unique=true, nullable=false)
    public Integer getBookingTrackingStatusId() {
        return this.bookingTrackingStatusId;
    }
    
    public void setBookingTrackingStatusId(Integer bookingTrackingStatusId) {
        this.bookingTrackingStatusId = bookingTrackingStatusId;
    }

    
    @Column(name="status_name", length=100)
    public String getStatusName() {
        return this.statusName;
    }
    
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bookingTrackingStatus")
    public Set<BookingTracking> getBookingTrackings() {
        return this.bookingTrackings;
    }
    
    public void setBookingTrackings(Set<BookingTracking> bookingTrackings) {
        this.bookingTrackings = bookingTrackings;
    }




}


