package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bookings generated by hbm2java
 */
@Entity
@Table(name="bookings"
    ,catalog="kemuvin"
)
public class Bookings  implements java.io.Serializable {


     private Long bookingId;
     private BookingStatusTypes bookingStatusTypes;
     private long vehicleId;
     private Long userSubscriptionId;
     private Date bookingDatetime;
     private Date startDate;
     private Date startTime;
     private Set<BookingTracking> bookingTrackings = new HashSet<BookingTracking>(0);
     private Set<VendorAcceptedBookings> vendorAcceptedBookingses = new HashSet<VendorAcceptedBookings>(0);

    public Bookings() {
    }

	
    public Bookings(long vehicleId, Date bookingDatetime) {
        this.vehicleId = vehicleId;
        this.bookingDatetime = bookingDatetime;
    }
    public Bookings(BookingStatusTypes bookingStatusTypes, long vehicleId, Long userSubscriptionId, Date bookingDatetime, Date startDate, Date startTime, Set<BookingTracking> bookingTrackings, Set<VendorAcceptedBookings> vendorAcceptedBookingses) {
       this.bookingStatusTypes = bookingStatusTypes;
       this.vehicleId = vehicleId;
       this.userSubscriptionId = userSubscriptionId;
       this.bookingDatetime = bookingDatetime;
       this.startDate = startDate;
       this.startTime = startTime;
       this.bookingTrackings = bookingTrackings;
       this.vendorAcceptedBookingses = vendorAcceptedBookingses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="booking_id", unique=true, nullable=false)
    public Long getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(Long bookingId) {
        this.bookingId = bookingId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="booking_status_type_id")
    public BookingStatusTypes getBookingStatusTypes() {
        return this.bookingStatusTypes;
    }
    
    public void setBookingStatusTypes(BookingStatusTypes bookingStatusTypes) {
        this.bookingStatusTypes = bookingStatusTypes;
    }

    
    @Column(name="vehicle_id", nullable=false)
    public long getVehicleId() {
        return this.vehicleId;
    }
    
    public void setVehicleId(long vehicleId) {
        this.vehicleId = vehicleId;
    }

    
    @Column(name="user_subscription_id")
    public Long getUserSubscriptionId() {
        return this.userSubscriptionId;
    }
    
    public void setUserSubscriptionId(Long userSubscriptionId) {
        this.userSubscriptionId = userSubscriptionId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="booking_datetime", nullable=false, length=19)
    public Date getBookingDatetime() {
        return this.bookingDatetime;
    }
    
    public void setBookingDatetime(Date bookingDatetime) {
        this.bookingDatetime = bookingDatetime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="start_time", length=8)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bookings")
    public Set<BookingTracking> getBookingTrackings() {
        return this.bookingTrackings;
    }
    
    public void setBookingTrackings(Set<BookingTracking> bookingTrackings) {
        this.bookingTrackings = bookingTrackings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bookings")
    public Set<VendorAcceptedBookings> getVendorAcceptedBookingses() {
        return this.vendorAcceptedBookingses;
    }
    
    public void setVendorAcceptedBookingses(Set<VendorAcceptedBookings> vendorAcceptedBookingses) {
        this.vendorAcceptedBookingses = vendorAcceptedBookingses;
    }




}


