package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BookingServiceId generated by hbm2java
 */
@Embeddable
public class BookingServiceId  implements java.io.Serializable {


     private long serviceId;
     private String serviceName;
     private String servicePeriod;
     private long bookingId;
     private Date startDate;

    public BookingServiceId() {
    }

	
    public BookingServiceId(long serviceId, String serviceName, long bookingId) {
        this.serviceId = serviceId;
        this.serviceName = serviceName;
        this.bookingId = bookingId;
    }
    public BookingServiceId(long serviceId, String serviceName, String servicePeriod, long bookingId, Date startDate) {
       this.serviceId = serviceId;
       this.serviceName = serviceName;
       this.servicePeriod = servicePeriod;
       this.bookingId = bookingId;
       this.startDate = startDate;
    }
   


    @Column(name="service_id", nullable=false)
    public long getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(long serviceId) {
        this.serviceId = serviceId;
    }


    @Column(name="service_name", nullable=false, length=100)
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }


    @Column(name="service_period", length=100)
    public String getServicePeriod() {
        return this.servicePeriod;
    }
    
    public void setServicePeriod(String servicePeriod) {
        this.servicePeriod = servicePeriod;
    }


    @Column(name="booking_id", nullable=false)
    public long getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(long bookingId) {
        this.bookingId = bookingId;
    }


    @Column(name="start_date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BookingServiceId) ) return false;
		 BookingServiceId castOther = ( BookingServiceId ) other; 
         
		 return (this.getServiceId()==castOther.getServiceId())
 && ( (this.getServiceName()==castOther.getServiceName()) || ( this.getServiceName()!=null && castOther.getServiceName()!=null && this.getServiceName().equals(castOther.getServiceName()) ) )
 && ( (this.getServicePeriod()==castOther.getServicePeriod()) || ( this.getServicePeriod()!=null && castOther.getServicePeriod()!=null && this.getServicePeriod().equals(castOther.getServicePeriod()) ) )
 && (this.getBookingId()==castOther.getBookingId())
 && ( (this.getStartDate()==castOther.getStartDate()) || ( this.getStartDate()!=null && castOther.getStartDate()!=null && this.getStartDate().equals(castOther.getStartDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getServiceId();
         result = 37 * result + ( getServiceName() == null ? 0 : this.getServiceName().hashCode() );
         result = 37 * result + ( getServicePeriod() == null ? 0 : this.getServicePeriod().hashCode() );
         result = 37 * result + (int) this.getBookingId();
         result = 37 * result + ( getStartDate() == null ? 0 : this.getStartDate().hashCode() );
         return result;
   }   


}


