package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BookingTracking generated by hbm2java
 */
@Entity
@Table(name="booking_tracking"
    ,catalog="kemuvin"
)
public class BookingTracking  implements java.io.Serializable {


     private Long bookingTrackingId;
     private Bookings bookings;
     private VehicleImageStatus vehicleImageStatus;
     private Services services;
     private BookingTrackingStatus bookingTrackingStatus;
     private Date startDatetime;
     private Date endDatetime;
     private String description;

    public BookingTracking() {
    }

    public BookingTracking(Bookings bookings, VehicleImageStatus vehicleImageStatus, Services services, BookingTrackingStatus bookingTrackingStatus, Date startDatetime, Date endDatetime, String description) {
       this.bookings = bookings;
       this.vehicleImageStatus = vehicleImageStatus;
       this.services = services;
       this.bookingTrackingStatus = bookingTrackingStatus;
       this.startDatetime = startDatetime;
       this.endDatetime = endDatetime;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="booking_tracking_id", unique=true, nullable=false)
    public Long getBookingTrackingId() {
        return this.bookingTrackingId;
    }
    
    public void setBookingTrackingId(Long bookingTrackingId) {
        this.bookingTrackingId = bookingTrackingId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="booking_id")
    public Bookings getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Bookings bookings) {
        this.bookings = bookings;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicle_image_status_id")
    public VehicleImageStatus getVehicleImageStatus() {
        return this.vehicleImageStatus;
    }
    
    public void setVehicleImageStatus(VehicleImageStatus vehicleImageStatus) {
        this.vehicleImageStatus = vehicleImageStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="service_id")
    public Services getServices() {
        return this.services;
    }
    
    public void setServices(Services services) {
        this.services = services;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="booking_tracking_status_id")
    public BookingTrackingStatus getBookingTrackingStatus() {
        return this.bookingTrackingStatus;
    }
    
    public void setBookingTrackingStatus(BookingTrackingStatus bookingTrackingStatus) {
        this.bookingTrackingStatus = bookingTrackingStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_datetime", length=19)
    public Date getStartDatetime() {
        return this.startDatetime;
    }
    
    public void setStartDatetime(Date startDatetime) {
        this.startDatetime = startDatetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_datetime", length=19)
    public Date getEndDatetime() {
        return this.endDatetime;
    }
    
    public void setEndDatetime(Date endDatetime) {
        this.endDatetime = endDatetime;
    }

    
    @Column(name="description", length=16777215)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


