package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BookingStatusTypes generated by hbm2java
 */
@Entity
@Table(name="booking_status_types"
    ,catalog="kemuvin"
)
public class BookingStatusTypes  implements java.io.Serializable {


     private Integer bookingStatusTypeId;
     private String bookingStatusType;
     private Set<Bookings> bookingses = new HashSet<Bookings>(0);

    public BookingStatusTypes() {
    }

    public BookingStatusTypes(String bookingStatusType, Set<Bookings> bookingses) {
       this.bookingStatusType = bookingStatusType;
       this.bookingses = bookingses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="booking_status_type_id", unique=true, nullable=false)
    public Integer getBookingStatusTypeId() {
        return this.bookingStatusTypeId;
    }
    
    public void setBookingStatusTypeId(Integer bookingStatusTypeId) {
        this.bookingStatusTypeId = bookingStatusTypeId;
    }

    
    @Column(name="booking_status_type", length=100)
    public String getBookingStatusType() {
        return this.bookingStatusType;
    }
    
    public void setBookingStatusType(String bookingStatusType) {
        this.bookingStatusType = bookingStatusType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bookingStatusTypes")
    public Set<Bookings> getBookingses() {
        return this.bookingses;
    }
    
    public void setBookingses(Set<Bookings> bookingses) {
        this.bookingses = bookingses;
    }




}


