package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BookingService generated by hbm2java
 */
@Entity
@Table(name="booking_service"
    ,catalog="kemuvin"
)
public class BookingService  implements java.io.Serializable {


     private BookingServiceId id;

    public BookingService() {
    }

    public BookingService(BookingServiceId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="serviceId", column=@Column(name="service_id", nullable=false) ), 
        @AttributeOverride(name="serviceName", column=@Column(name="service_name", nullable=false, length=100) ), 
        @AttributeOverride(name="servicePeriod", column=@Column(name="service_period", length=100) ), 
        @AttributeOverride(name="bookingId", column=@Column(name="booking_id", nullable=false) ), 
        @AttributeOverride(name="startDate", column=@Column(name="start_date", length=10) ) } )
    public BookingServiceId getId() {
        return this.id;
    }
    
    public void setId(BookingServiceId id) {
        this.id = id;
    }




}


