package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Brands generated by hbm2java
 */
@Entity
@Table(name="brands"
    ,catalog="kemuvin"
)
public class Brands  implements java.io.Serializable {


     private Long brandId;
     private VehicleCategories vehicleCategories;
     private String brandName;
     private Boolean inTrending;
     private String brandImageName;
     private String brandImagePath;
     private Boolean activeBrand;
     private Set<Models> modelses = new HashSet<Models>(0);

    public Brands() {
    }

    public Brands(VehicleCategories vehicleCategories, String brandName, Boolean inTrending, String brandImageName, String brandImagePath, Boolean activeBrand, Set<Models> modelses) {
       this.vehicleCategories = vehicleCategories;
       this.brandName = brandName;
       this.inTrending = inTrending;
       this.brandImageName = brandImageName;
       this.brandImagePath = brandImagePath;
       this.activeBrand = activeBrand;
       this.modelses = modelses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="brand_id", unique=true, nullable=false)
    public Long getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicle_category_id")
    public VehicleCategories getVehicleCategories() {
        return this.vehicleCategories;
    }
    
    public void setVehicleCategories(VehicleCategories vehicleCategories) {
        this.vehicleCategories = vehicleCategories;
    }

    
    @Column(name="brand_name", length=100)
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    
    @Column(name="in_trending")
    public Boolean getInTrending() {
        return this.inTrending;
    }
    
    public void setInTrending(Boolean inTrending) {
        this.inTrending = inTrending;
    }

    
    @Column(name="brand_image_name", length=100)
    public String getBrandImageName() {
        return this.brandImageName;
    }
    
    public void setBrandImageName(String brandImageName) {
        this.brandImageName = brandImageName;
    }

    
    @Column(name="brand_image_path", length=100)
    public String getBrandImagePath() {
        return this.brandImagePath;
    }
    
    public void setBrandImagePath(String brandImagePath) {
        this.brandImagePath = brandImagePath;
    }

    
    @Column(name="active_brand")
    public Boolean getActiveBrand() {
        return this.activeBrand;
    }
    
    public void setActiveBrand(Boolean activeBrand) {
        this.activeBrand = activeBrand;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="brands")
    public Set<Models> getModelses() {
        return this.modelses;
    }
    
    public void setModelses(Set<Models> modelses) {
        this.modelses = modelses;
    }




}


