package com.me.models;
// Generated 28 Mar, 2025 6:48:35 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name="course"
    ,catalog="college"
)
public class Course  implements java.io.Serializable {


     private int id;
     private String course;

    public Course() {
    }

	
    public Course(int id) {
        this.id = id;
    }
    public Course(int id, String course) {
       this.id = id;
       this.course = course;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="course", length=50)
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }




}


