package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Databasechangeloglock generated by hbm2java
 */
@Entity
@Table(name="databasechangeloglock"
    ,catalog="kemuvin"
)
public class Databasechangeloglock  implements java.io.Serializable {


     private int id;
     private byte locked;
     private Date lockgranted;
     private String lockedby;

    public Databasechangeloglock() {
    }

	
    public Databasechangeloglock(int id, byte locked) {
        this.id = id;
        this.locked = locked;
    }
    public Databasechangeloglock(int id, byte locked, Date lockgranted, String lockedby) {
       this.id = id;
       this.locked = locked;
       this.lockgranted = lockgranted;
       this.lockedby = lockedby;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="LOCKED", nullable=false)
    public byte getLocked() {
        return this.locked;
    }
    
    public void setLocked(byte locked) {
        this.locked = locked;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LOCKGRANTED", length=19)
    public Date getLockgranted() {
        return this.lockgranted;
    }
    
    public void setLockgranted(Date lockgranted) {
        this.lockgranted = lockgranted;
    }

    
    @Column(name="LOCKEDBY")
    public String getLockedby() {
        return this.lockedby;
    }
    
    public void setLockedby(String lockedby) {
        this.lockedby = lockedby;
    }




}


