package com.me.models;
// Generated 28 Mar, 2025 6:48:35 PM by Hibernate Tools 4.0.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dept generated by hbm2java
 */
@Entity
@Table(name="dept"
    ,catalog="college"
)
public class Dept  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<Teacher> teachers = new HashSet<Teacher>(0);

    public Dept() {
    }

	
    public Dept(int id) {
        this.id = id;
    }
    public Dept(int id, String name, Set<Teacher> teachers) {
       this.id = id;
       this.name = name;
       this.teachers = teachers;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dept")
    public Set<Teacher> getTeachers() {
        return this.teachers;
    }
    
    public void setTeachers(Set<Teacher> teachers) {
        this.teachers = teachers;
    }




}


