package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FuelTypes generated by hbm2java
 */
@Entity
@Table(name="fuel_types"
    ,catalog="kemuvin"
)
public class FuelTypes  implements java.io.Serializable {


     private Integer fuelTypeId;
     private String fuelType;
     private Set<Models> modelses = new HashSet<Models>(0);

    public FuelTypes() {
    }

    public FuelTypes(String fuelType, Set<Models> modelses) {
       this.fuelType = fuelType;
       this.modelses = modelses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="fuel_type_id", unique=true, nullable=false)
    public Integer getFuelTypeId() {
        return this.fuelTypeId;
    }
    
    public void setFuelTypeId(Integer fuelTypeId) {
        this.fuelTypeId = fuelTypeId;
    }

    
    @Column(name="fuel_type", length=100)
    public String getFuelType() {
        return this.fuelType;
    }
    
    public void setFuelType(String fuelType) {
        this.fuelType = fuelType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fuelTypes")
    public Set<Models> getModelses() {
        return this.modelses;
    }
    
    public void setModelses(Set<Models> modelses) {
        this.modelses = modelses;
    }




}


