package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Models generated by hbm2java
 */
@Entity
@Table(name="models"
    ,catalog="kemuvin"
)
public class Models  implements java.io.Serializable {


     private Long modelId;
     private VehicleTypes vehicleTypes;
     private FuelTypes fuelTypes;
     private Brands brands;
     private VehicleCategories vehicleCategories;
     private String modelName;
     private String model;
     private Integer modelYear;
     private Boolean activeModel;
     private Set<Vehicles> vehicleses = new HashSet<Vehicles>(0);

    public Models() {
    }

	
    public Models(FuelTypes fuelTypes, VehicleCategories vehicleCategories, String modelName, String model) {
        this.fuelTypes = fuelTypes;
        this.vehicleCategories = vehicleCategories;
        this.modelName = modelName;
        this.model = model;
    }
    public Models(VehicleTypes vehicleTypes, FuelTypes fuelTypes, Brands brands, VehicleCategories vehicleCategories, String modelName, String model, Integer modelYear, Boolean activeModel, Set<Vehicles> vehicleses) {
       this.vehicleTypes = vehicleTypes;
       this.fuelTypes = fuelTypes;
       this.brands = brands;
       this.vehicleCategories = vehicleCategories;
       this.modelName = modelName;
       this.model = model;
       this.modelYear = modelYear;
       this.activeModel = activeModel;
       this.vehicleses = vehicleses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="model_id", unique=true, nullable=false)
    public Long getModelId() {
        return this.modelId;
    }
    
    public void setModelId(Long modelId) {
        this.modelId = modelId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicle_type_id")
    public VehicleTypes getVehicleTypes() {
        return this.vehicleTypes;
    }
    
    public void setVehicleTypes(VehicleTypes vehicleTypes) {
        this.vehicleTypes = vehicleTypes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fuel_type_id", nullable=false)
    public FuelTypes getFuelTypes() {
        return this.fuelTypes;
    }
    
    public void setFuelTypes(FuelTypes fuelTypes) {
        this.fuelTypes = fuelTypes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="brand_id")
    public Brands getBrands() {
        return this.brands;
    }
    
    public void setBrands(Brands brands) {
        this.brands = brands;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicle_category_id", nullable=false)
    public VehicleCategories getVehicleCategories() {
        return this.vehicleCategories;
    }
    
    public void setVehicleCategories(VehicleCategories vehicleCategories) {
        this.vehicleCategories = vehicleCategories;
    }

    
    @Column(name="model_name", nullable=false, length=100)
    public String getModelName() {
        return this.modelName;
    }
    
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    
    @Column(name="model", nullable=false, length=100)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }

    
    @Column(name="model_year")
    public Integer getModelYear() {
        return this.modelYear;
    }
    
    public void setModelYear(Integer modelYear) {
        this.modelYear = modelYear;
    }

    
    @Column(name="active_model")
    public Boolean getActiveModel() {
        return this.activeModel;
    }
    
    public void setActiveModel(Boolean activeModel) {
        this.activeModel = activeModel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="models")
    public Set<Vehicles> getVehicleses() {
        return this.vehicleses;
    }
    
    public void setVehicleses(Set<Vehicles> vehicleses) {
        this.vehicleses = vehicleses;
    }




}


