package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OneTimePassword generated by hbm2java
 */
@Entity
@Table(name="one_time_password"
    ,catalog="kemuvin"
)
public class OneTimePassword  implements java.io.Serializable {


     private Long oneTimePasswordId;
     private String otpValue;
     private Date otpExpires;
     private Date otpGeneratedDatetime;
     private String otpUid;
     private long toNumber;

    public OneTimePassword() {
    }

    public OneTimePassword(String otpValue, Date otpExpires, Date otpGeneratedDatetime, String otpUid, long toNumber) {
       this.otpValue = otpValue;
       this.otpExpires = otpExpires;
       this.otpGeneratedDatetime = otpGeneratedDatetime;
       this.otpUid = otpUid;
       this.toNumber = toNumber;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="one_time_password_id", unique=true, nullable=false)
    public Long getOneTimePasswordId() {
        return this.oneTimePasswordId;
    }
    
    public void setOneTimePasswordId(Long oneTimePasswordId) {
        this.oneTimePasswordId = oneTimePasswordId;
    }

    
    @Column(name="otp_value", nullable=false, length=100)
    public String getOtpValue() {
        return this.otpValue;
    }
    
    public void setOtpValue(String otpValue) {
        this.otpValue = otpValue;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="otp_expires", nullable=false, length=19)
    public Date getOtpExpires() {
        return this.otpExpires;
    }
    
    public void setOtpExpires(Date otpExpires) {
        this.otpExpires = otpExpires;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="otp_generated_datetime", nullable=false, length=19)
    public Date getOtpGeneratedDatetime() {
        return this.otpGeneratedDatetime;
    }
    
    public void setOtpGeneratedDatetime(Date otpGeneratedDatetime) {
        this.otpGeneratedDatetime = otpGeneratedDatetime;
    }

    
    @Column(name="otp_uid", nullable=false, length=100)
    public String getOtpUid() {
        return this.otpUid;
    }
    
    public void setOtpUid(String otpUid) {
        this.otpUid = otpUid;
    }

    
    @Column(name="to_number", nullable=false)
    public long getToNumber() {
        return this.toNumber;
    }
    
    public void setToNumber(long toNumber) {
        this.toNumber = toNumber;
    }




}


