package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RoleTypes generated by hbm2java
 */
@Entity
@Table(name="role_types"
    ,catalog="kemuvin"
)
public class RoleTypes  implements java.io.Serializable {


     private Integer roleTypeId;
     private String roleType;
     private Set<Roles> roleses = new HashSet<Roles>(0);

    public RoleTypes() {
    }

    public RoleTypes(String roleType, Set<Roles> roleses) {
       this.roleType = roleType;
       this.roleses = roleses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="role_type_id", unique=true, nullable=false)
    public Integer getRoleTypeId() {
        return this.roleTypeId;
    }
    
    public void setRoleTypeId(Integer roleTypeId) {
        this.roleTypeId = roleTypeId;
    }

    
    @Column(name="role_type", length=100)
    public String getRoleType() {
        return this.roleType;
    }
    
    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="roleTypes")
    public Set<Roles> getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set<Roles> roleses) {
        this.roleses = roleses;
    }




}


