package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="roles"
    ,catalog="kemuvin"
)
public class Roles  implements java.io.Serializable {


     private Integer roleId;
     private RoleTypes roleTypes;
     private String roleName;
     private Set<Vendors> vendorses = new HashSet<Vendors>(0);
     private Set<Users> userses = new HashSet<Users>(0);
     private Set<VendorEmployees> vendorEmployeeses = new HashSet<VendorEmployees>(0);

    public Roles() {
    }

    public Roles(RoleTypes roleTypes, String roleName, Set<Vendors> vendorses, Set<Users> userses, Set<VendorEmployees> vendorEmployeeses) {
       this.roleTypes = roleTypes;
       this.roleName = roleName;
       this.vendorses = vendorses;
       this.userses = userses;
       this.vendorEmployeeses = vendorEmployeeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="role_id", unique=true, nullable=false)
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_type_id")
    public RoleTypes getRoleTypes() {
        return this.roleTypes;
    }
    
    public void setRoleTypes(RoleTypes roleTypes) {
        this.roleTypes = roleTypes;
    }

    
    @Column(name="role_name", length=100)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="roles")
    public Set<Vendors> getVendorses() {
        return this.vendorses;
    }
    
    public void setVendorses(Set<Vendors> vendorses) {
        this.vendorses = vendorses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="roles")
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="roles")
    public Set<VendorEmployees> getVendorEmployeeses() {
        return this.vendorEmployeeses;
    }
    
    public void setVendorEmployeeses(Set<VendorEmployees> vendorEmployeeses) {
        this.vendorEmployeeses = vendorEmployeeses;
    }




}


