package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name="services"
    ,catalog="kemuvin"
)
public class Services  implements java.io.Serializable {


     private Long serviceId;
     private ServiceSubCategories serviceSubCategories;
     private String serviceName;
     private Set<VendorServices> vendorServiceses = new HashSet<VendorServices>(0);
     private Set<SubscriptionPlanDetails> subscriptionPlanDetailses = new HashSet<SubscriptionPlanDetails>(0);
     private Set<BookingTracking> bookingTrackings = new HashSet<BookingTracking>(0);

    public Services() {
    }

	
    public Services(String serviceName) {
        this.serviceName = serviceName;
    }
    public Services(ServiceSubCategories serviceSubCategories, String serviceName, Set<VendorServices> vendorServiceses, Set<SubscriptionPlanDetails> subscriptionPlanDetailses, Set<BookingTracking> bookingTrackings) {
       this.serviceSubCategories = serviceSubCategories;
       this.serviceName = serviceName;
       this.vendorServiceses = vendorServiceses;
       this.subscriptionPlanDetailses = subscriptionPlanDetailses;
       this.bookingTrackings = bookingTrackings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="service_id", unique=true, nullable=false)
    public Long getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(Long serviceId) {
        this.serviceId = serviceId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="service_sub_category_id")
    public ServiceSubCategories getServiceSubCategories() {
        return this.serviceSubCategories;
    }
    
    public void setServiceSubCategories(ServiceSubCategories serviceSubCategories) {
        this.serviceSubCategories = serviceSubCategories;
    }

    
    @Column(name="service_name", nullable=false, length=100)
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="services")
    public Set<VendorServices> getVendorServiceses() {
        return this.vendorServiceses;
    }
    
    public void setVendorServiceses(Set<VendorServices> vendorServiceses) {
        this.vendorServiceses = vendorServiceses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="services")
    public Set<SubscriptionPlanDetails> getSubscriptionPlanDetailses() {
        return this.subscriptionPlanDetailses;
    }
    
    public void setSubscriptionPlanDetailses(Set<SubscriptionPlanDetails> subscriptionPlanDetailses) {
        this.subscriptionPlanDetailses = subscriptionPlanDetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="services")
    public Set<BookingTracking> getBookingTrackings() {
        return this.bookingTrackings;
    }
    
    public void setBookingTrackings(Set<BookingTracking> bookingTrackings) {
        this.bookingTrackings = bookingTrackings;
    }




}


