package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ServicesCategories generated by hbm2java
 */
@Entity
@Table(name="services_categories"
    ,catalog="kemuvin"
)
public class ServicesCategories  implements java.io.Serializable {


     private Integer servicesCategoryId;
     private String servicesCategory;
     private Set<ServiceSubCategories> serviceSubCategorieses = new HashSet<ServiceSubCategories>(0);

    public ServicesCategories() {
    }

	
    public ServicesCategories(String servicesCategory) {
        this.servicesCategory = servicesCategory;
    }
    public ServicesCategories(String servicesCategory, Set<ServiceSubCategories> serviceSubCategorieses) {
       this.servicesCategory = servicesCategory;
       this.serviceSubCategorieses = serviceSubCategorieses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="services_category_id", unique=true, nullable=false)
    public Integer getServicesCategoryId() {
        return this.servicesCategoryId;
    }
    
    public void setServicesCategoryId(Integer servicesCategoryId) {
        this.servicesCategoryId = servicesCategoryId;
    }

    
    @Column(name="services_category", nullable=false, length=100)
    public String getServicesCategory() {
        return this.servicesCategory;
    }
    
    public void setServicesCategory(String servicesCategory) {
        this.servicesCategory = servicesCategory;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="servicesCategories")
    public Set<ServiceSubCategories> getServiceSubCategorieses() {
        return this.serviceSubCategorieses;
    }
    
    public void setServiceSubCategorieses(Set<ServiceSubCategories> serviceSubCategorieses) {
        this.serviceSubCategorieses = serviceSubCategorieses;
    }




}


