package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Slots generated by hbm2java
 */
@Entity
@Table(name="slots"
    ,catalog="kemuvin"
)
public class Slots  implements java.io.Serializable {


     private Long slotId;
     private Date openingTime;
     private Date closingTime;
     private String daysOfTheWeek;
     private Long vendorId;

    public Slots() {
    }

    public Slots(Date openingTime, Date closingTime, String daysOfTheWeek, Long vendorId) {
       this.openingTime = openingTime;
       this.closingTime = closingTime;
       this.daysOfTheWeek = daysOfTheWeek;
       this.vendorId = vendorId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="slot_id", unique=true, nullable=false)
    public Long getSlotId() {
        return this.slotId;
    }
    
    public void setSlotId(Long slotId) {
        this.slotId = slotId;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="opening_time", length=8)
    public Date getOpeningTime() {
        return this.openingTime;
    }
    
    public void setOpeningTime(Date openingTime) {
        this.openingTime = openingTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="closing_time", length=8)
    public Date getClosingTime() {
        return this.closingTime;
    }
    
    public void setClosingTime(Date closingTime) {
        this.closingTime = closingTime;
    }

    
    @Column(name="days_of_the_week", length=100)
    public String getDaysOfTheWeek() {
        return this.daysOfTheWeek;
    }
    
    public void setDaysOfTheWeek(String daysOfTheWeek) {
        this.daysOfTheWeek = daysOfTheWeek;
    }

    
    @Column(name="vendor_id")
    public Long getVendorId() {
        return this.vendorId;
    }
    
    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }




}


