package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SmsCountryAudit generated by hbm2java
 */
@Entity
@Table(name="sms_country_audit"
    ,catalog="kemuvin"
)
public class SmsCountryAudit  implements java.io.Serializable {


     private Long smsCountryAuditId;
     private String requestUrl;
     private String requestBody;
     private String responseBody;
     private Date requestDatetime;
     private Date responseDatetime;

    public SmsCountryAudit() {
    }

    public SmsCountryAudit(String requestUrl, String requestBody, String responseBody, Date requestDatetime, Date responseDatetime) {
       this.requestUrl = requestUrl;
       this.requestBody = requestBody;
       this.responseBody = responseBody;
       this.requestDatetime = requestDatetime;
       this.responseDatetime = responseDatetime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sms_country_audit_id", unique=true, nullable=false)
    public Long getSmsCountryAuditId() {
        return this.smsCountryAuditId;
    }
    
    public void setSmsCountryAuditId(Long smsCountryAuditId) {
        this.smsCountryAuditId = smsCountryAuditId;
    }

    
    @Column(name="request_url", length=16777215)
    public String getRequestUrl() {
        return this.requestUrl;
    }
    
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl;
    }

    
    @Column(name="request_body", length=16777215)
    public String getRequestBody() {
        return this.requestBody;
    }
    
    public void setRequestBody(String requestBody) {
        this.requestBody = requestBody;
    }

    
    @Column(name="response_body", length=16777215)
    public String getResponseBody() {
        return this.responseBody;
    }
    
    public void setResponseBody(String responseBody) {
        this.responseBody = responseBody;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="request_datetime", length=19)
    public Date getRequestDatetime() {
        return this.requestDatetime;
    }
    
    public void setRequestDatetime(Date requestDatetime) {
        this.requestDatetime = requestDatetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="response_datetime", length=19)
    public Date getResponseDatetime() {
        return this.responseDatetime;
    }
    
    public void setResponseDatetime(Date responseDatetime) {
        this.responseDatetime = responseDatetime;
    }




}


