package com.me.models;
// Generated 28 Mar, 2025 6:48:35 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Stu generated by hbm2java
 */
@Entity
@Table(name="stu"
    ,catalog="college"
)
public class Stu  implements java.io.Serializable {


     private int rollno;
     private String name;
     private int marks;
     private String grade;
     private String city;

    public Stu() {
    }

	
    public Stu(int rollno, int marks) {
        this.rollno = rollno;
        this.marks = marks;
    }
    public Stu(int rollno, String name, int marks, String grade, String city) {
       this.rollno = rollno;
       this.name = name;
       this.marks = marks;
       this.grade = grade;
       this.city = city;
    }
   
     @Id 

    
    @Column(name="rollno", unique=true, nullable=false)
    public int getRollno() {
        return this.rollno;
    }
    
    public void setRollno(int rollno) {
        this.rollno = rollno;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="marks", nullable=false)
    public int getMarks() {
        return this.marks;
    }
    
    public void setMarks(int marks) {
        this.marks = marks;
    }

    
    @Column(name="grade", length=1)
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }

    
    @Column(name="city", length=20)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }




}


