package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SubscriptionPlanDetails generated by hbm2java
 */
@Entity
@Table(name="subscription_plan_details"
    ,catalog="kemuvin"
)
public class SubscriptionPlanDetails  implements java.io.Serializable {


     private Integer subscriptionPlanDetailId;
     private SubscriptionPlans subscriptionPlans;
     private Services services;
     private String servicePeriod;

    public SubscriptionPlanDetails() {
    }

    public SubscriptionPlanDetails(SubscriptionPlans subscriptionPlans, Services services, String servicePeriod) {
       this.subscriptionPlans = subscriptionPlans;
       this.services = services;
       this.servicePeriod = servicePeriod;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="subscription_plan_detail_id", unique=true, nullable=false)
    public Integer getSubscriptionPlanDetailId() {
        return this.subscriptionPlanDetailId;
    }
    
    public void setSubscriptionPlanDetailId(Integer subscriptionPlanDetailId) {
        this.subscriptionPlanDetailId = subscriptionPlanDetailId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="subscription_plan_id")
    public SubscriptionPlans getSubscriptionPlans() {
        return this.subscriptionPlans;
    }
    
    public void setSubscriptionPlans(SubscriptionPlans subscriptionPlans) {
        this.subscriptionPlans = subscriptionPlans;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="service_id")
    public Services getServices() {
        return this.services;
    }
    
    public void setServices(Services services) {
        this.services = services;
    }

    
    @Column(name="service_period", length=100)
    public String getServicePeriod() {
        return this.servicePeriod;
    }
    
    public void setServicePeriod(String servicePeriod) {
        this.servicePeriod = servicePeriod;
    }




}


