package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SubscriptionPlans generated by hbm2java
 */
@Entity
@Table(name="subscription_plans"
    ,catalog="kemuvin"
)
public class SubscriptionPlans  implements java.io.Serializable {


     private Integer subscriptionPlanId;
     private String subscriptionName;
     private Long price;
     private Boolean recommended;
     private Set<SubscriptionPlanDetails> subscriptionPlanDetailses = new HashSet<SubscriptionPlanDetails>(0);
     private Set<UserSubscriptions> userSubscriptionses = new HashSet<UserSubscriptions>(0);

    public SubscriptionPlans() {
    }

    public SubscriptionPlans(String subscriptionName, Long price, Boolean recommended, Set<SubscriptionPlanDetails> subscriptionPlanDetailses, Set<UserSubscriptions> userSubscriptionses) {
       this.subscriptionName = subscriptionName;
       this.price = price;
       this.recommended = recommended;
       this.subscriptionPlanDetailses = subscriptionPlanDetailses;
       this.userSubscriptionses = userSubscriptionses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="subscription_plan_id", unique=true, nullable=false)
    public Integer getSubscriptionPlanId() {
        return this.subscriptionPlanId;
    }
    
    public void setSubscriptionPlanId(Integer subscriptionPlanId) {
        this.subscriptionPlanId = subscriptionPlanId;
    }

    
    @Column(name="subscription_name", length=100)
    public String getSubscriptionName() {
        return this.subscriptionName;
    }
    
    public void setSubscriptionName(String subscriptionName) {
        this.subscriptionName = subscriptionName;
    }

    
    @Column(name="price", precision=10, scale=0)
    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }

    
    @Column(name="recommended")
    public Boolean getRecommended() {
        return this.recommended;
    }
    
    public void setRecommended(Boolean recommended) {
        this.recommended = recommended;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subscriptionPlans")
    public Set<SubscriptionPlanDetails> getSubscriptionPlanDetailses() {
        return this.subscriptionPlanDetailses;
    }
    
    public void setSubscriptionPlanDetailses(Set<SubscriptionPlanDetails> subscriptionPlanDetailses) {
        this.subscriptionPlanDetailses = subscriptionPlanDetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subscriptionPlans")
    public Set<UserSubscriptions> getUserSubscriptionses() {
        return this.userSubscriptionses;
    }
    
    public void setUserSubscriptionses(Set<UserSubscriptions> userSubscriptionses) {
        this.userSubscriptionses = userSubscriptionses;
    }




}


