package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserConfirmedBookings generated by hbm2java
 */
@Entity
@Table(name="user_confirmed_bookings"
    ,catalog="kemuvin"
)
public class UserConfirmedBookings  implements java.io.Serializable {


     private UserConfirmedBookingsId id;

    public UserConfirmedBookings() {
    }

    public UserConfirmedBookings(UserConfirmedBookingsId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="bookingId", column=@Column(name="booking_id", nullable=false) ), 
        @AttributeOverride(name="startDate", column=@Column(name="start_date", length=10) ), 
        @AttributeOverride(name="startTime", column=@Column(name="start_time", length=8) ), 
        @AttributeOverride(name="subscriptionPlanId", column=@Column(name="subscription_plan_id", nullable=false) ), 
        @AttributeOverride(name="subscriptionName", column=@Column(name="subscription_name", length=100) ), 
        @AttributeOverride(name="price", column=@Column(name="price", precision=10, scale=0) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ), 
        @AttributeOverride(name="vehicleId", column=@Column(name="vehicle_id", nullable=false) ), 
        @AttributeOverride(name="vehicleNumber", column=@Column(name="vehicle_number", length=100) ), 
        @AttributeOverride(name="formattedAddress", column=@Column(name="formatted_address", length=65535) ), 
        @AttributeOverride(name="brandName", column=@Column(name="brand_name", length=100) ), 
        @AttributeOverride(name="modelName", column=@Column(name="model_name", nullable=false, length=100) ) } )
    public UserConfirmedBookingsId getId() {
        return this.id;
    }
    
    public void setId(UserConfirmedBookingsId id) {
        this.id = id;
    }




}


