package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserSubscriptions generated by hbm2java
 */
@Entity
@Table(name="user_subscriptions"
    ,catalog="kemuvin"
)
public class UserSubscriptions  implements java.io.Serializable {


     private Long userSubscriptionId;
     private SubscriptionPlans subscriptionPlans;
     private Users users;
     private Vehicles vehicles;
     private Date subscribedDatetime;

    public UserSubscriptions() {
    }

	
    public UserSubscriptions(SubscriptionPlans subscriptionPlans, Users users, Date subscribedDatetime) {
        this.subscriptionPlans = subscriptionPlans;
        this.users = users;
        this.subscribedDatetime = subscribedDatetime;
    }
    public UserSubscriptions(SubscriptionPlans subscriptionPlans, Users users, Vehicles vehicles, Date subscribedDatetime) {
       this.subscriptionPlans = subscriptionPlans;
       this.users = users;
       this.vehicles = vehicles;
       this.subscribedDatetime = subscribedDatetime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_subscription_id", unique=true, nullable=false)
    public Long getUserSubscriptionId() {
        return this.userSubscriptionId;
    }
    
    public void setUserSubscriptionId(Long userSubscriptionId) {
        this.userSubscriptionId = userSubscriptionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="subscription_plan_id", nullable=false)
    public SubscriptionPlans getSubscriptionPlans() {
        return this.subscriptionPlans;
    }
    
    public void setSubscriptionPlans(SubscriptionPlans subscriptionPlans) {
        this.subscriptionPlans = subscriptionPlans;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicle_id")
    public Vehicles getVehicles() {
        return this.vehicles;
    }
    
    public void setVehicles(Vehicles vehicles) {
        this.vehicles = vehicles;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="subscribed_datetime", nullable=false, length=19)
    public Date getSubscribedDatetime() {
        return this.subscribedDatetime;
    }
    
    public void setSubscribedDatetime(Date subscribedDatetime) {
        this.subscribedDatetime = subscribedDatetime;
    }




}


