package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vehicles generated by hbm2java
 */
@Entity
@Table(name="vehicles"
    ,catalog="kemuvin"
)
public class Vehicles  implements java.io.Serializable {


     private Long vehicleId;
     private Models models;
     private Users users;
     private Date addedDatetime;
     private String vehicleNumber;
     private Set<UserSubscriptions> userSubscriptionses = new HashSet<UserSubscriptions>(0);

    public Vehicles() {
    }

	
    public Vehicles(Users users) {
        this.users = users;
    }
    public Vehicles(Models models, Users users, Date addedDatetime, String vehicleNumber, Set<UserSubscriptions> userSubscriptionses) {
       this.models = models;
       this.users = users;
       this.addedDatetime = addedDatetime;
       this.vehicleNumber = vehicleNumber;
       this.userSubscriptionses = userSubscriptionses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="vehicle_id", unique=true, nullable=false)
    public Long getVehicleId() {
        return this.vehicleId;
    }
    
    public void setVehicleId(Long vehicleId) {
        this.vehicleId = vehicleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="model_id")
    public Models getModels() {
        return this.models;
    }
    
    public void setModels(Models models) {
        this.models = models;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="added_datetime", length=19)
    public Date getAddedDatetime() {
        return this.addedDatetime;
    }
    
    public void setAddedDatetime(Date addedDatetime) {
        this.addedDatetime = addedDatetime;
    }

    
    @Column(name="vehicle_number", length=100)
    public String getVehicleNumber() {
        return this.vehicleNumber;
    }
    
    public void setVehicleNumber(String vehicleNumber) {
        this.vehicleNumber = vehicleNumber;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vehicles")
    public Set<UserSubscriptions> getUserSubscriptionses() {
        return this.userSubscriptionses;
    }
    
    public void setUserSubscriptionses(Set<UserSubscriptions> userSubscriptionses) {
        this.userSubscriptionses = userSubscriptionses;
    }




}


