package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VehicleServiceDetails generated by hbm2java
 */
@Entity
@Table(name="vehicle_service_details"
    ,catalog="kemuvin"
)
public class VehicleServiceDetails  implements java.io.Serializable {


     private VehicleServiceDetailsId id;

    public VehicleServiceDetails() {
    }

    public VehicleServiceDetails(VehicleServiceDetailsId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vehicleId", column=@Column(name="vehicle_id", nullable=false) ), 
        @AttributeOverride(name="vehicleNumber", column=@Column(name="vehicle_number", length=100) ), 
        @AttributeOverride(name="vehicleCategory", column=@Column(name="vehicle_category", length=100) ), 
        @AttributeOverride(name="model", column=@Column(name="model", nullable=false, length=100) ), 
        @AttributeOverride(name="modelName", column=@Column(name="model_name", nullable=false, length=100) ), 
        @AttributeOverride(name="brandName", column=@Column(name="brand_name", length=100) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ), 
        @AttributeOverride(name="totalDueAmount", column=@Column(name="total_due_amount", precision=32, scale=0) ) } )
    public VehicleServiceDetailsId getId() {
        return this.id;
    }
    
    public void setId(VehicleServiceDetailsId id) {
        this.id = id;
    }




}


