package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VehicleTypes generated by hbm2java
 */
@Entity
@Table(name="vehicle_types"
    ,catalog="kemuvin"
)
public class VehicleTypes  implements java.io.Serializable {


     private Integer vehicleTypeId;
     private String vehicleType;
     private Set<Models> modelses = new HashSet<Models>(0);

    public VehicleTypes() {
    }

    public VehicleTypes(String vehicleType, Set<Models> modelses) {
       this.vehicleType = vehicleType;
       this.modelses = modelses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="vehicle_type_id", unique=true, nullable=false)
    public Integer getVehicleTypeId() {
        return this.vehicleTypeId;
    }
    
    public void setVehicleTypeId(Integer vehicleTypeId) {
        this.vehicleTypeId = vehicleTypeId;
    }

    
    @Column(name="vehicle_type", length=100)
    public String getVehicleType() {
        return this.vehicleType;
    }
    
    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vehicleTypes")
    public Set<Models> getModelses() {
        return this.modelses;
    }
    
    public void setModelses(Set<Models> modelses) {
        this.modelses = modelses;
    }




}


