package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VehicleViewTypes generated by hbm2java
 */
@Entity
@Table(name="vehicle_view_types"
    ,catalog="kemuvin"
)
public class VehicleViewTypes  implements java.io.Serializable {


     private Integer vehicleViewTypeId;
     private String vehicleViewType;
     private Set<VehicleImageStatus> vehicleImageStatuses = new HashSet<VehicleImageStatus>(0);

    public VehicleViewTypes() {
    }

    public VehicleViewTypes(String vehicleViewType, Set<VehicleImageStatus> vehicleImageStatuses) {
       this.vehicleViewType = vehicleViewType;
       this.vehicleImageStatuses = vehicleImageStatuses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="vehicle_view_type_id", unique=true, nullable=false)
    public Integer getVehicleViewTypeId() {
        return this.vehicleViewTypeId;
    }
    
    public void setVehicleViewTypeId(Integer vehicleViewTypeId) {
        this.vehicleViewTypeId = vehicleViewTypeId;
    }

    
    @Column(name="vehicle_view_type", length=100)
    public String getVehicleViewType() {
        return this.vehicleViewType;
    }
    
    public void setVehicleViewType(String vehicleViewType) {
        this.vehicleViewType = vehicleViewType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vehicleViewTypes")
    public Set<VehicleImageStatus> getVehicleImageStatuses() {
        return this.vehicleImageStatuses;
    }
    
    public void setVehicleImageStatuses(Set<VehicleImageStatus> vehicleImageStatuses) {
        this.vehicleImageStatuses = vehicleImageStatuses;
    }




}


