package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendorEmployees generated by hbm2java
 */
@Entity
@Table(name="vendor_employees"
    ,catalog="kemuvin"
)
public class VendorEmployees  implements java.io.Serializable {


     private Long vendorEmployeeId;
     private Roles roles;
     private Vendors vendors;
     private String firstName;
     private String lastName;
     private String email;
     private Long phoneNumber;
     private Date joinDate;

    public VendorEmployees() {
    }

    public VendorEmployees(Roles roles, Vendors vendors, String firstName, String lastName, String email, Long phoneNumber, Date joinDate) {
       this.roles = roles;
       this.vendors = vendors;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.joinDate = joinDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="vendor_employee_id", unique=true, nullable=false)
    public Long getVendorEmployeeId() {
        return this.vendorEmployeeId;
    }
    
    public void setVendorEmployeeId(Long vendorEmployeeId) {
        this.vendorEmployeeId = vendorEmployeeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id")
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendor_id")
    public Vendors getVendors() {
        return this.vendors;
    }
    
    public void setVendors(Vendors vendors) {
        this.vendors = vendors;
    }

    
    @Column(name="first_name", length=100)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=100)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone_number")
    public Long getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(Long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="join_date", length=10)
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }




}


