package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VendorEarningsOnVehicle generated by hbm2java
 */
@Entity
@Table(name="vendor_earnings_on_vehicle"
    ,catalog="kemuvin"
)
public class VendorEarningsOnVehicle  implements java.io.Serializable {


     private VendorEarningsOnVehicleId id;

    public VendorEarningsOnVehicle() {
    }

    public VendorEarningsOnVehicle(VendorEarningsOnVehicleId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vehicleId", column=@Column(name="vehicle_id", nullable=false) ), 
        @AttributeOverride(name="vehicleNumber", column=@Column(name="vehicle_number", length=100) ), 
        @AttributeOverride(name="vehicleCategory", column=@Column(name="vehicle_category", length=100) ), 
        @AttributeOverride(name="model", column=@Column(name="model", nullable=false, length=100) ), 
        @AttributeOverride(name="modelName", column=@Column(name="model_name", nullable=false, length=100) ), 
        @AttributeOverride(name="brandName", column=@Column(name="brand_name", length=100) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ), 
        @AttributeOverride(name="vendorId", column=@Column(name="vendor_id") ), 
        @AttributeOverride(name="totalEarnAmount", column=@Column(name="total_earn_amount", precision=32, scale=0) ) } )
    public VendorEarningsOnVehicleId getId() {
        return this.id;
    }
    
    public void setId(VendorEarningsOnVehicleId id) {
        this.id = id;
    }




}


