package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VendorEarningsOnVehicleId generated by hbm2java
 */
@Embeddable
public class VendorEarningsOnVehicleId  implements java.io.Serializable {


     private long vehicleId;
     private String vehicleNumber;
     private String vehicleCategory;
     private String model;
     private String modelName;
     private String brandName;
     private long userId;
     private Long vendorId;
     private BigDecimal totalEarnAmount;

    public VendorEarningsOnVehicleId() {
    }

	
    public VendorEarningsOnVehicleId(long vehicleId, String model, String modelName, long userId) {
        this.vehicleId = vehicleId;
        this.model = model;
        this.modelName = modelName;
        this.userId = userId;
    }
    public VendorEarningsOnVehicleId(long vehicleId, String vehicleNumber, String vehicleCategory, String model, String modelName, String brandName, long userId, Long vendorId, BigDecimal totalEarnAmount) {
       this.vehicleId = vehicleId;
       this.vehicleNumber = vehicleNumber;
       this.vehicleCategory = vehicleCategory;
       this.model = model;
       this.modelName = modelName;
       this.brandName = brandName;
       this.userId = userId;
       this.vendorId = vendorId;
       this.totalEarnAmount = totalEarnAmount;
    }
   


    @Column(name="vehicle_id", nullable=false)
    public long getVehicleId() {
        return this.vehicleId;
    }
    
    public void setVehicleId(long vehicleId) {
        this.vehicleId = vehicleId;
    }


    @Column(name="vehicle_number", length=100)
    public String getVehicleNumber() {
        return this.vehicleNumber;
    }
    
    public void setVehicleNumber(String vehicleNumber) {
        this.vehicleNumber = vehicleNumber;
    }


    @Column(name="vehicle_category", length=100)
    public String getVehicleCategory() {
        return this.vehicleCategory;
    }
    
    public void setVehicleCategory(String vehicleCategory) {
        this.vehicleCategory = vehicleCategory;
    }


    @Column(name="model", nullable=false, length=100)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }


    @Column(name="model_name", nullable=false, length=100)
    public String getModelName() {
        return this.modelName;
    }
    
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }


    @Column(name="brand_name", length=100)
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }


    @Column(name="user_id", nullable=false)
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }


    @Column(name="vendor_id")
    public Long getVendorId() {
        return this.vendorId;
    }
    
    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }


    @Column(name="total_earn_amount", precision=32, scale=0)
    public BigDecimal getTotalEarnAmount() {
        return this.totalEarnAmount;
    }
    
    public void setTotalEarnAmount(BigDecimal totalEarnAmount) {
        this.totalEarnAmount = totalEarnAmount;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VendorEarningsOnVehicleId) ) return false;
		 VendorEarningsOnVehicleId castOther = ( VendorEarningsOnVehicleId ) other; 
         
		 return (this.getVehicleId()==castOther.getVehicleId())
 && ( (this.getVehicleNumber()==castOther.getVehicleNumber()) || ( this.getVehicleNumber()!=null && castOther.getVehicleNumber()!=null && this.getVehicleNumber().equals(castOther.getVehicleNumber()) ) )
 && ( (this.getVehicleCategory()==castOther.getVehicleCategory()) || ( this.getVehicleCategory()!=null && castOther.getVehicleCategory()!=null && this.getVehicleCategory().equals(castOther.getVehicleCategory()) ) )
 && ( (this.getModel()==castOther.getModel()) || ( this.getModel()!=null && castOther.getModel()!=null && this.getModel().equals(castOther.getModel()) ) )
 && ( (this.getModelName()==castOther.getModelName()) || ( this.getModelName()!=null && castOther.getModelName()!=null && this.getModelName().equals(castOther.getModelName()) ) )
 && ( (this.getBrandName()==castOther.getBrandName()) || ( this.getBrandName()!=null && castOther.getBrandName()!=null && this.getBrandName().equals(castOther.getBrandName()) ) )
 && (this.getUserId()==castOther.getUserId())
 && ( (this.getVendorId()==castOther.getVendorId()) || ( this.getVendorId()!=null && castOther.getVendorId()!=null && this.getVendorId().equals(castOther.getVendorId()) ) )
 && ( (this.getTotalEarnAmount()==castOther.getTotalEarnAmount()) || ( this.getTotalEarnAmount()!=null && castOther.getTotalEarnAmount()!=null && this.getTotalEarnAmount().equals(castOther.getTotalEarnAmount()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getVehicleId();
         result = 37 * result + ( getVehicleNumber() == null ? 0 : this.getVehicleNumber().hashCode() );
         result = 37 * result + ( getVehicleCategory() == null ? 0 : this.getVehicleCategory().hashCode() );
         result = 37 * result + ( getModel() == null ? 0 : this.getModel().hashCode() );
         result = 37 * result + ( getModelName() == null ? 0 : this.getModelName().hashCode() );
         result = 37 * result + ( getBrandName() == null ? 0 : this.getBrandName().hashCode() );
         result = 37 * result + (int) this.getUserId();
         result = 37 * result + ( getVendorId() == null ? 0 : this.getVendorId().hashCode() );
         result = 37 * result + ( getTotalEarnAmount() == null ? 0 : this.getTotalEarnAmount().hashCode() );
         return result;
   }   


}


