package com.me.models;
// Generated Jan 6, 2025 12:39:00 PM by Hibernate Tools 4.0.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vendors generated by hbm2java
 */
@Entity
@Table(name="vendors"
    ,catalog="kemuvin"
)
public class Vendors  implements java.io.Serializable {


     private Long vendorId;
     private Roles roles;
     private VendorTypes vendorTypes;
     private String vendorName;
     private String lastName;
     private String firstName;
     private String email;
     private Boolean activeVendor;
     private Long phoneNumber;
     private String expoNotificationToken;
     private Set<VendorAcceptedBookings> vendorAcceptedBookingses = new HashSet<VendorAcceptedBookings>(0);
     private Set<VendorEmployees> vendorEmployeeses = new HashSet<VendorEmployees>(0);
     private Set<VendorServices> vendorServiceses = new HashSet<VendorServices>(0);

    public Vendors() {
    }

    public Vendors(Roles roles, VendorTypes vendorTypes, String vendorName, String lastName, String firstName, String email, Boolean activeVendor, Long phoneNumber, String expoNotificationToken, Set<VendorAcceptedBookings> vendorAcceptedBookingses, Set<VendorEmployees> vendorEmployeeses, Set<VendorServices> vendorServiceses) {
       this.roles = roles;
       this.vendorTypes = vendorTypes;
       this.vendorName = vendorName;
       this.lastName = lastName;
       this.firstName = firstName;
       this.email = email;
       this.activeVendor = activeVendor;
       this.phoneNumber = phoneNumber;
       this.expoNotificationToken = expoNotificationToken;
       this.vendorAcceptedBookingses = vendorAcceptedBookingses;
       this.vendorEmployeeses = vendorEmployeeses;
       this.vendorServiceses = vendorServiceses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="vendor_id", unique=true, nullable=false)
    public Long getVendorId() {
        return this.vendorId;
    }
    
    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id")
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendor_type_id")
    public VendorTypes getVendorTypes() {
        return this.vendorTypes;
    }
    
    public void setVendorTypes(VendorTypes vendorTypes) {
        this.vendorTypes = vendorTypes;
    }

    
    @Column(name="vendor_name", length=100)
    public String getVendorName() {
        return this.vendorName;
    }
    
    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }

    
    @Column(name="last_name", length=100)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="first_name", length=100)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="active_vendor")
    public Boolean getActiveVendor() {
        return this.activeVendor;
    }
    
    public void setActiveVendor(Boolean activeVendor) {
        this.activeVendor = activeVendor;
    }

    
    @Column(name="phone_number")
    public Long getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(Long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="expo_notification_token", length=100)
    public String getExpoNotificationToken() {
        return this.expoNotificationToken;
    }
    
    public void setExpoNotificationToken(String expoNotificationToken) {
        this.expoNotificationToken = expoNotificationToken;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendors")
    public Set<VendorAcceptedBookings> getVendorAcceptedBookingses() {
        return this.vendorAcceptedBookingses;
    }
    
    public void setVendorAcceptedBookingses(Set<VendorAcceptedBookings> vendorAcceptedBookingses) {
        this.vendorAcceptedBookingses = vendorAcceptedBookingses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendors")
    public Set<VendorEmployees> getVendorEmployeeses() {
        return this.vendorEmployeeses;
    }
    
    public void setVendorEmployeeses(Set<VendorEmployees> vendorEmployeeses) {
        this.vendorEmployeeses = vendorEmployeeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendors")
    public Set<VendorServices> getVendorServiceses() {
        return this.vendorServiceses;
    }
    
    public void setVendorServiceses(Set<VendorServices> vendorServiceses) {
        this.vendorServiceses = vendorServiceses;
    }




}


